### ISSUE TITLE
Count of members holding TH in admin does not match our Missing Member page

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#204]
195 "Missing Members" via our admin tool. 166 on our public Missing Member page.

**Comment by meganrm** [comment]
Hey, so it looks like how you looked up missing members on the admin page is by looking at all the town halls that have occurred and then counting up the number of people that havent' had town halls. I wouldn't expect this to exactly match up but we can dig into it more. The way the "Missing Member" tag got assigned is from the list that was researched before that was 196 (I think). But there were people who weren't included on that list even though we hadn't listed an event for them, since our research was incomplete. And since that time, if a town hall gets posted on the site they get taken off the list automatically. I'll get a list of the people that we dont have a town hall event for but are not listed as official missing members and see if it checks out.
