### ISSUE TITLE
Add Campaign Header style

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#259]
![header error](https://user-images.githubusercontent.com/25805849/34806364-54c39162-f637-11e7-8418-4ebac7b28229.JPG)

**Comment by pdvorchik** [comment]
We're missing styles for the panel background and the icon.  The second only seems to be working because it showing up as "in person" -- but they actually should have both been missing.

@nathanmwilliams @meganrm do we have a color picked out for this?

Partially blocked by #262 as we're going to need the icon here as well.

Relevant classes for future travelers:
`.panel-heading_campaign` and `.event-icon__campaign`

**Comment by meganrm** [comment]
it should match the color of the icon, @DylanMoriarty can you post the svg file?
