### ISSUE TITLE
Is email on page working? 

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallProject#78]
In my chrome and firefox it just reloads the page without any change.

**Comment by meganrm** [comment]
hey, is this still the case for you @nathanmwilliams? Is anyone else having problems?

**Comment by nathanmwilliams** [comment]
Yeah, nothing happens for me.

**Comment by arjavrawal** [comment]
Chrome user here, nothing happening.

**Comment by JSP64** [comment]
Hi @meganrm and @nathanmwilliams - my name is Jonah Phillips and I'm looking to start contributing. 

It looks like `mailto` is unreliable since it depends on the user's mail configuration, and additionally there doesn't seem to be a reliable way to detect when it fails: [http://stackoverflow.com/questions/7214686/detecting-when-mailto-failed].

I see two options:
1. Show an overlay when the mail button is clicked that includes the email address, so the information is provided even if the mailto link doesn't work
2. Eliminate the mail button and show the email address under the fax number on the representative card

I'd lean toward option 2 as being most user-friendly and simplest, but maybe there was a reason you didn't want to do it this way initially?  Let me know which approach you prefer and I will create a branch for this.

**Comment by nathanmwilliams** [comment]
Personally I am a "simplest is usually best" person. So #2 sounds good to me. Though I defer to @meganrm, as there may have been a reason we didn't go this route initially.

**Comment by pdvorchik** [comment]
Ideally the solution should also work for mailto in the navbar, which the text link wouldn't really accomplish.

**Comment by arjavrawal** [comment]
Perhaps we could just use a form for contact instead of a mailto??

**Comment by meganrm** [comment]
For the rep cards: 
@JSP64 I think #2 makes sense.
For our own email:
@arjavrawal I like the idea of a contact form.

**Comment by nathanmwilliams** [comment]
I like a form.

**Comment by arjavrawal** [comment]
For the rep cards, how about we directly link them to their rep's online contact form? That way if they aren't a constituent they can't send mail, allowing more interaction between constituents and their own offices.

**Comment by pdvorchik** [comment]
@meganrm When you have a second can you help me figure out what I broke with the routing?  Branch is #78-contact-form https://github.com/townhallproject/townHallProject/tree/%2378-Contact-Form

I pretty obviously messed something up -- email icons remain toggled after clicking them once and they no longer work.  And using the inline links doesn't reset the state (if I click the link in #about it shows the form but hash stays in #about).

Besides that?  I'm just waiting @nathanmwilliams to give me a list of what emails to send the various subjects to so I know they're being routed correctly.  Also free to request copy changes.

Most of the actual emailing logic is complete.

**Comment by pdvorchik** [comment]
Video of the bugs in action:

[THP-Routing.zip](https://github.com/townhallproject/townHallProject/files/916847/THP-Routing.zip)
